apollographql/react-apollo

README.md

Which are we going with? Looks like the npm package is `react-apollo`, which means the docs need to be updated here either way.

apollo-react vs react-apollo

---

Changelog
package.json
src/connect.tsx
test/connect.tsx

Discussion in #30 
cc @abhiaiyer91

remove result in favor of the key's returned by the query

---

Changelog.md
package.json
src/connect.tsx
test/connect/mutations.tsx
test/connect/queries.tsx

This PR does a few things (it can be split up if needed).
Fixes #41 and #20
cc @stubailo @johnthepink

Performance improvements, and better lifecycle support

---

Changelog.md
src/connect.tsx
test/connect/mutations.tsx

Originally queries and mutations pull from the same default values for consistency. It doesn't really make sense that `loading` would be true on mutations until they are called so this PR fixes that.
Original issue and disucssion: #64

set the default loading state on mutations to be false

---

Changelog.md
src/connect.tsx
test/connect/queries.tsx

When a refetched query returned the same data as the original, the loading state wasn't correctly being updated.

Hotfix refetch loading state

---

Changelog.md
package.json
src/connect.tsx
test/connect/queries.tsx

use up to date props on state change

---

Changelog.md
src/connect.tsx
test/connect/props.tsx
test/connect/redux.tsx

I was recently looking for a way to subscribe to `watchQuery` directly, rather than through the usual `mapQueriesToProps`, and noticed that, while `query` and `mutate` are passed via `connect`, `watchQuery` is not. This PR changes that.

Provide watchQuery to components via connect.

---

Changelog.md
package.json
src/connect.tsx
test/client/connect/queries.tsx

This should finally fix #57 
With patterns from https://github.com/reactjs/react-redux/commit/ea53d6fb076359a864a1d543568d951d4b3eab3d

Error catching

---

src/ApolloProvider.tsx
test/client/ApolloProvider.tsx

The current error just states that it `"can't read initStore of undefined"`, which is a pretty cryptic error if you're not familiar with the internals of `ApolloProvider`.
This just throws a more friendly error.

Throw an error if the client is missing

---

global.d.ts
package.json
src/connect.tsx
test/client/connect/statics.tsx

Currently, `react-apollo`'s `@connect` strips any custom statics from the components it wraps; this'll preserve them, using the [same method employed by `react-redux`](https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L365).

Have @connect hoist statics

---

src/connect.tsx

Don't strip data away from the component when the query errors

---

package.json
src/connect.tsx
typings/modules/apollo-client/index.d.ts
typings/modules/apollo-client/typings.json

A few hacks we should fixe before merging

Update to apollo client 0.4.0

---

src/connect.tsx
test/client/connect/queries.tsx

This fixes an issue where if there is a server or network error during `refetch()`, the query state reported by `react-apollo` would be stuck `loading: true, errors: undefined` until some other (unrelated) query executes (and bumps the store)

Ensure that loading state and errors are consistently propagated when calling refetch()

---

Changelog.md
package.json
src/server.ts
test/react-web/server/index.tsx

Fix context issues on SSR

---

src/graphql.tsx
test/react-web/server/index.tsx

Run into this issue when was toying with React Router + Apollo SSR example, please check the test for the details

Bugfix: graphql wrapper doesnt work with fragments (SSR)

---

src/graphql.tsx

remove option of passing client as props and fix error message accordingly
Closes https://github.com/apollostack/react-apollo/issues/183

Simplify apollo client access

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/queries.tsx
test/react-web/client/libraries/redux.tsx

Fixes https://github.com/apollostack/react-apollo/issues/170

fix indefinite loading on remount with null data

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/queries.tsx

Fixes https://github.com/apollostack/react-apollo/issues/197
cc @tmeasday

allow optional variables

---

Changelog.md
package.json
src/server.ts
test/react-web/server/index.tsx

fix ssr issues with lifecycle events

---

src/server.ts

Just in case one's using an immutable store.

Use client store.

---

src/graphql.tsx
src/server.ts

I hope I got it well. It may or may not require major bump.
I'd be really glad if you released it asap, as I use my own redux store.

Use getApolloState instead relying on reduxRootKey

---

test/mocks/mockNetworkInterface.ts

Sometimes AC will send `variables: {}` now.

---

.travis.yml
preprocessor.js

The `npm test` infrastructure seemed to have broken for Node 4, though we still think that the distribution worked (because it targeted ES5 in tsconfig.json).

Support Node 4 for tests

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/queries-1.test.tsx
test/react-web/server/index.test.tsx

Fixes #245 
Docs PR https://github.com/apollostack/react-docs/pull/70
TODO:

New skip method

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/queries-1.test.tsx

Also delete querySubscription when there is no subscription, since that
seems reasonable.
See #255.

Fix crash in unsubscribeFromQuery

---

Changelog.md
src/graphql.tsx
test/react-web/server/index.test.tsx
typings.d.ts

We were hoisting `fetchData` onto the mutation HOC, which led to the
query executing twice
Fixes #274.
Going to take a look at the open SSR issue on this branch too.

Fix issue with SSR on a mutation wrapping a query

---

Changelog.md
src/graphql.tsx
test/react-native/component.test.js
test/react-web/client/graphql/fragments.test.tsx
test/react-web/client/graphql/mutations.test.tsx
test/react-web/client/graphql/queries-1.test.tsx
test/react-web/client/graphql/queries-2.test.tsx
test/react-web/client/graphql/shared-operations-1.test.tsx
test/react-web/client/graphql/shared-operations-2.test.tsx
test/react-web/client/graphql/subscriptions.test.tsx
test/react-web/client/libraries/mobx.test.tsx
test/react-web/client/libraries/redux-1.test.tsx
test/react-web/client/libraries/redux-2.test.tsx
test/react-web/server/index.test.tsx

Blockers:
- One mutation test failure from https://github.com/apollostack/apollo-client/pull/801
Tests passing:
TODO:

Update to Apollo Client 0.5

---

Changelog.md
package.json
src/index.ts
typings.d.ts

Fixes #279 
As suggested by @migueloller `compose` is re-exported from `redux` instead of `recompose`, since implementation is completely the same, that's why we can drop depending on `recompose` completely.
TODO:

Fix issue with usage in TypeScript projects caused by 'compose' re-export

---

Changelog.md
src/graphql.tsx
test/react-web/server/index.test.tsx

Fix forceFetch on SSR

---

package.json
src/server.ts
test/react-web/server/index.test.tsx
yarn.lock

Refactored SSR to use a slightly more principled `walkTree` method.
Tests pass, some points of interest:
1. I got rid of returning the `context` from the SSR functions. This seemed kind of undefined (what was it? The lowest context we saw in the tree? Should we have been just picking the first `ApolloProvider` child context we saw?). All in all it seemed a bit hacky, and the user will have access to an `ApolloClient` anyway, so can't they just get the store themselves?
- this will require a docs change.
2. I am still assigning `instance.setState`. This seems to *not* throw an exception. How does this fit your understanding @rewop? I was surprised by this but we need to do something like this to allow people to call `setState` in `componentWillMount` (or pursue a different method of …

Refactor ssr

---

package.json
src/graphql.tsx
test/react-web/client/graphql/mutations.test.tsx
test/react-web/client/graphql/queries-1.test.tsx
test/react-web/client/graphql/shared-operations-1.test.tsx
test/react-web/server/index.test.tsx
yarn.lock

WIP for #264 
Issues outstanding
1. I think `observableQuery.currentResult()` should return `errors` also. Need to PR AC for that.
2. Slight weirdness with needing to store `previousData`. Moving forward we should just be able to blindly pass `currentResult` through; perhaps AC should cache `previousData`. But hopefully what I'm doing works for now.
3. A bunch of tests failing, some due to the above, need to investigate more.

Refactor to calculate data at render time

---

Changelog.md
examples/create-react-app/src/App.js
examples/create-react-app/src/Pokemon.js
examples/create-react-app/src/Pokemon.test.js
package.json
src/browser.ts
src/index.ts
tsconfig.json

Provide compiled sources from 'lib' for node modules. Provide all API exports from index.js.
This is breaking change.
As a side effect this change fixes file paths in Stack Traces when react-apollo throws exceptions.

Better packaging utilizing package.json browser field

---

Changelog.md
test/react-web/client/graphql/queries.test.tsx

This just gets rid of warning on the queries.test.
TODO:
- [x ] Make sure all of the significant new logic is covered by tests
- [ x] Rebase your changes on master so that they can be merged easily
- [ x] Make sure all tests and linter rules pass
- [ x] Update CHANGELOG.md with your change

gets rid of queries.test warning

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/subscriptions.test.tsx

A should resubscribe option makes subscription queries optionally resubscribe when the props change..
I use it like this:
````
const NODE_SUBSCRIPTION_QUERY = gql`
subscription  - blah blah ....
const NODE_QUERY = gql`
query  - blah blah ....
const _Node = (props) => <Blah />
const options = {
shouldResubscribe: (props, nextProps) => {
// if the id property changes then we need to resubscribe..
return nextProps.id !== props.id
}
}
const Node = compose(
graphql(NODE_SUBSCRIPTION_QUERY, options),
graphql(NODE_QUERY)
)(_Node)
````

add shouldResubscribe option

---

package.json

This clears up the error on React Native.

Move react-dom to optionalDependencies, fix #402

---

package.json
src/graphql.tsx
test/react-web/client/graphql/queries.test.tsx
yarn.lock

Mirror the behaviour for the original query, which is to pass the error via the `error` prop, not let a promise exception reach the top of the stack.
https://github.com/apollostack/react-apollo/issues/404

Silently catch errors for changing variables

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/shared-operations.test.tsx

Issue #331.
Re-using the `graphql`'s `OperationOption` interface only for its `withRef` option may not make a lot of sense?

withRef option for withApollo HoC

---

Changelog.md
README.md
src/graphql.tsx
test/react-web/client/graphql/queries.test.tsx

As explained in https://github.com/apollostack/react-apollo/issues/354, your React component tree can get quite confusing when you have many nested `Apollo(...)` containers. This PR adds an `alias` option to the `graphql` HoC factory function:
```
options(ownProps) {
return {
alias: 'withCurrentUser',
};
},
```
Before:
After: 
TODO:

Add an `alias` option to `graphql` container

---

.vscode/settings.json
package.json
src/graphql.tsx
test/react-web/client/ApolloProvider.test.tsx
test/react-web/server/index.test.tsx

This PR will fix the failing tests on `master`, and mute the warnings Jest emit.
The reason tests were failing was because Parse finally went offline! So the old GraphQL SWAPI API we hit in the tests (http://graphql-swapi.parseapp.com/) is no longer reachable. The new SWAPI is hosted on https://graphql.org/swapi-graphql, but now the [schema](http://graphql.org/swapi-graphql/schema.js) runs entirely on the client and not the server. This means there was no URL to point to.
It’s probably not a good idea that we were sending a network request to someone else’s server in our tests anyway, so this PR refactors the test in question to use a local schema.
This PR also hides expected errors from `PropTypes` in tests and upgrades Jest to fix some errors that were being logged.

Fix failing tests on `master`

---

src/parser.ts
test/parser.test.ts
test/react-web/client/graphql/fragments.test.tsx

This fixes the problems identified in #453.

Fixed bugs around invariants

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/mutations.test.tsx
test/react-web/client/graphql/queries.test.tsx
tsconfig.json

This PR is our first attempt to solve the `updateQueries` regression introduced by `apollo-client` version `0.5.22` in a bug fix while still trying to keep the bug that got fixed, well, fixed.
The issue is that when `updateQueries` or a `reducer` references data for a component which has been unmounted then there is no way to update data in the store at that location. So say you had an app where the user moved to a comment entry screen and your comments list component was unmounted. The user enters a comment and submits a mutation with an `updateQueries` that references the query for the unmounted comments list component. The `updateQueries` function would not run in this environment because of our bug fix.
Before `0.5.22` line [502 of …

Add recycling for `ObservableQuery`s

---

Changelog.md
package.json
src/index.ts
test/lib.test.ts
yarn.lock

WIP: Include peers

---

Changelog.md
examples/create-react-app/src/Pokemon.test.js
package.json
src/test-utils.tsx

`graphql-tag` has deprecated the export of the `printer` export (which we use for various AST-related tasks here in `react-apollo`). when `graphql-tag@v2` comes out, we can switch to using the printer / parser from the `graphql` package, but for now we know about the deprecation warning and can safely ignore it.
addresses [graphql-tag#54](https://github.com/apollographql/graphql-tag/issues/54)
TODO:

Bumping `graphql-tag`, ignoring deprecation warnings

---

src/graphql.tsx

As documented in: 
https://github.com/apollographql/react-apollo/issues/174
https://github.com/apollographql/apollo-client/issues/764
https://github.com/HriBB/react-apollo-rhl-problem
Hot Module Replacement doesn't work when your component is wrapped by the GraphQL HOC. This happens because `render()` reutilizes `this.renderedElement` even though the `WrappedComponent` implementation changed during hot reloading.

Check if WrappedComponent implementation changed since last render to fix HMR

---

Changelog.md
src/graphql.tsx

React outputs setState warnings (constructor side-effects are an anti-pattern), because of that initializing of props in the constructor and by moving that code to componentWillMount fixes that.

fix: Move constructor initializing of props to componentWillMount

---

src/graphql.tsx
test/react-web/client/graphql/queries.test.tsx

I just like “Unhandled (in react-apollo) Error …” more than “Uncaught (in react-apollo) Error …” At first I only used “uncaught” to be symmetrical with uncaught promise errors, but I have changed my mind that symmetry is important 😊

Change uncaught to unhandled

---

Changelog.md
package.json
src/graphql.tsx
test/react-web/client/graphql/queries.test.tsx
test/react-web/server/index.test.tsx

1.0.0 rc.2

---

Changelog.md
package.json
src/ApolloProvider.tsx
src/graphql.tsx
src/test-utils.tsx
test/react-native/__snapshots__/component.test.js.snap
test/react-web/client/ApolloProvider.test.tsx
test/react-web/client/graphql/queries.test.tsx

We have a use case in React Native where we switch the GraphQL endpoint dynamically while the app is running. This PR changes the ApolloProvider API by updating it's client and store when new props are delivered to the provider.
TODO:

Allow ApolloProvider Prop Updates

---

Changelog.md
src/test-utils.tsx

MockedProvider did not pass any `store` prop down to the ApolloProvider where it can be handled appropriately. This caused the MockedProvider to override the redux store and cause my tests to fail. 
This change simply passes it along so that ApolloProvider can use it like normal.
Also fixed a typo.

fix: Pass store prop from MockedProvider to ApolloProvider for parity

---

Changelog.md
src/browser.ts
src/index.ts

Exposed `createBatchingNetworkInterface` from apollo-client so that it can be imported from react-apollo just like `createNetworkInterface`.
TODO:

exposed createBatchingNetworkInterface from apollo-client

---

Changelog.md
package.json
src/ApolloProvider.tsx
src/graphql.tsx
test/react-web/client/ApolloProvider.test.tsx
test/react-web/client/graphql/queries.test.tsx
test/react-web/server/index.test.tsx

Closes #623 
TODO:
- (**N/A**) If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- (**N/A**) Make sure all of the significant new logic is covered by tests
- (**N/A**) If this was a change that affects the external API, update the docs and post a link to the PR in the discussion
**Note:** There's a significant amount of existing lint errors in the test files, but I skipped over them since that is outside the scope of this PR. None are build-breaking because those files aren't actually linted during CI.

convert React.PropTypes to "prop-types" module

---

.travis.yml
package.json
scripts/filesize.js
scripts/gzip.js

Description
----------
Currently, react-apollo uses `gzip-size` to get the gzip size without writing a `.gz` file to disk. `travis-weigh-in` requires an actual file to work with, making it incompatible with `gzip-size`. 
To solve this, this PR replaces `gzip-size` with a simple script that saves the compressed gzip and uses that file for file size calculation for both `npm run filesize` and `travis-weigh-in` scripts. 
The compression strategy utilized by `/scripts/gzip.js` is identical to what's used in `gzip-size`, with both using `zlib` set to level 9. The main change is that `gzip.js` creates a `.gz` file.
Also, the added `.gz` file in `/dist` might be helpful for people wanting to use gzipped versions of `react-apollo` in development.
Summary of changes:
----------
- Add a simple …

Add script to create gzipped file in development & report gzip size on weigh in

---

src/ApolloProvider.tsx

Is causing issues when `ApolloProvider` is used with other Providers (eg: react-router).
`shouldComponentUpdate` is an unnecessary here, it is used to stop unnecessary updates caused by higher components. But as `ApolloProvider` should be near the top of the tree, it can be assumed that ALL updates passed to is are necessary.
fixes issue: #557

fix(shouldComponentUpdate): removed from ApolloProvider

---

Changelog.md
package.json

- Perf: Removed unneeded usage of shouldComponentUpdate [PR #661](https://github.com/apollographql/react-apollo/pull/661) inspired by [PR #653](https://github.com/apollographql/react-apollo/pull/653)
- Perf: Removed  unneeded usage of shouldComponentUpdate in Provider [PR #669](https://github.com/apollographql/react-apollo/pull/669)
- Chore: remove unused immutable prop [PR #539](https://github.com/apollographql/react-apollo/pull/539)

Release 1.1.3

---

src/graphql.tsx
src/test-utils.tsx

Moved to using root import for types from AC. Needs to wait on https://github.com/apollographql/apollo-client/pull/1644

move type imports to root of AC for easier local dev / ci testing

---

Changelog.md
package.json
src/graphql.tsx
test/react-web/client/graphql/mutations.test.tsx

See https://github.com/apollographql/react-apollo/issues/622
TODO:

Use standby fetchPolicy for recycled queries

---

Changelog.md
src/graphql.tsx
test/react-web/server/index.test.tsx

As discussed in #328.
I've added a test that passes now with the adapted logic in `graphql.tsx`. I'm not quite confident if it is the right way to go though, so I'd appreciate a review 🙂.
TODO:

Fix server side rendering when using the `cache-and-network` fetchPolicy

---

Changelog.md
package.json
src/graphql.tsx
test/react-web/client/graphql/queries/errors.test.tsx
test/react-web/client/graphql/queries/observableQuery.test.tsx

Fix for #718, #667, and probably a lot of other loading issues by removing the current subscription before recycling the observable 
I'm going to add a test in the morning for this, but for all those impacted, this will be released tomorrow after the flow PR is released in AC. 👍 
TODO:

recycled query teardown

---

index.js.flow

Fixes: [785](https://github.com/apollographql/react-apollo/issues/785)
TODO:

fixes flow error: "Named import from module 'react'"

---

Changelog.md
dangerfile.ts
package.json
src/browser.ts
src/graphql.tsx
src/queryRecycler.ts
src/types.ts
src/withApollo.tsx
test/typescript.ts

fixes #786 
fixes #809,
fixes #810.
Special thanks to @alexzielenski for [the comment](https://github.com/apollographql/react-apollo/issues/786#issuecomment-309249584) which helped to inform some of these fixes.
Official usage docs will be coming soon, but in the meantime, here is a sample of how to use some of the improved types:
```js
import * as React from 'react';
import gql from 'graphql-tag';
import { graphql } from '../src';
import { ChildProps, NamedProps, QueryProps } from '../src/types';
const historyQuery = gql`
query history($solutionId: String) {
history(solutionId: $solutionId) {
solutionId
delta
}
}
`;
type Data = {
history: Record<any, any>[];
};
type Props = {
solutionId: string;
};
// standard wrapping
const withHistory = graphql<Data, Props>(historyQuery, {
options: …
```

fix typescript usage

---

renovate.json

Renovate is currently configured to use the schedule "after 10pm and before 5am on every weekday" however without a configured "timezone" then these times will default to UTC. This PR adds the America/Los_Angeles IANA time zone to the `renovate.json` configuration file, assuming that's the preferred timezone for this schedule.

chore(deps): Add timezone to Renovate config

---

Changelog.md
package.json
src/index.ts
test/react-web/server/index.test.tsx

For some reason (I'd love someone to help me understand!) the 1.4.9 version of this library had a malformed UMD bundle where `getDataFromTree` was written as `apolloClient.getDataFromTree`?!
This fixes that issue and is already released

fix exports

---

src/index.js.flow

This should fix the Redux-related flowtype errors that are popping up in react-apollo due to incorrect usage of the Redux `Store` type in `index.js.flow`.
The error currently appears as:
```
node_modules/react-apollo/index.js.flow:30
30:     store: Store,
^^^^^ Store. Application of polymorphic type needs <list of 2 arguments>. (Can use `*` for inferrable ones)
```
This fix is basically adding inferred types (`*`) as arguments to all references to the Redux `Store` type inside of `index.js.flow`. This should fix #898.
Generally you want to pass in your State and Actions as arguments to `Store`. i.e.:
```javascript
type State = {
// ...
}
type Actions = {
// ...
}
const foo: Store<State, Actions> = // ...
```
... but seeing as how the usage of `Store` was incorrect to begin with, and in …

Fix Redux `Store` flow errors

---

Changelog.md
src/test-utils.tsx
test/react-web/client/graphql/queries/index.test.tsx

Currently mock data needs to exactly match the request being made within a component being tested. This is because requests object are [stringified](https://github.com/apollographql/react-apollo/blob/master/src/test-utils.tsx#L259-L266) and used as keys when [registering](https://github.com/apollographql/react-apollo/blob/master/src/test-utils.tsx#L121) and [looking up](https://github.com/apollographql/react-apollo/blob/master/src/test-utils.tsx#L138) the corresponding response objects to be returned. This change sorts the request object when it is stringified so the order of variables doesn't matter.
This issue is discussed in #674

MockNetworkInterface match mock requests regardless of variable order

---

Changelog.md
src/ApolloProvider.tsx
src/QueryRecyclerProvider.tsx
src/graphql.tsx
test/react-web/client/graphql/client-option.test.tsx

This PR addresses the issue https://github.com/apollographql/react-apollo/issues/513. I used a WeakMap as suggested in this conversation https://github.com/apollographql/react-apollo/pull/462#issuecomment-284306070, but I'm not sure if we should polyfill WeakMap.
I tried the code linking the package to my [playground](https://github.com/rcoedo/react-apollo-playground) and it works, but I'm a bit lost with the test structure of the project and I don't really know how to write a test for this feature.
Also I'm also quite new to Apollo and I've never touched Typescript before so I really appreciate all the feedback you can give 😄

Client scoped query recyclers (#513)

---

Changelog.md
examples/base/src/__tests__/App.js
src/test-utils.tsx

This PR allows to pass a removeTypenames prop to the MockedProvider, this way there's no need to add the __typename field to the mocked data.
Right now, to add mocked data in tests, it's required to use `addTypenameToDocument` in all of the queries:
```
const query = addTypenameToDocument(HERO_QUERY);
```
Together with this, the mocked data needs to include the __typename field in all of the models:
```
export const hero_no_friends = {
__typename: 'Droid',
name: 'r2d2',
id: '1',
friends: null,
};
```
I find this a bit of a pain, and I would prefer not having to do this. As the apollo-client accepts an `addTypename` field, we can allow the MockedProvider to configure that option as we'd like.
This can be used this like this:
```
<MockedProvider mocks={mocks} removeTypename>
```
I didn't …

Remove typenames from MockedProvider

---

Changelog.md
src/types.ts

This small PR fixes issue #896 - notifyOnNetworkStatusChange were missing from Typescript definitions of query and mutation options.

Added notifyOnNetworkStatusChange to QueryOpts and MutationOpts types

---

Changelog.md
src/types.ts
test/typescript.ts

Here is a small update on Typescript part, so we can type queries' & mutations' variables, as [apollo-codegen](https://github.com/apollographql/apollo-codegen) generates these types for us. Default values are used, so it shouldn't break any previous code.
I also added some tests to describe general usage.

Added variables types with Typescript

---

Changelog.md
src/types.ts

Make ChildProps.data non-optional

---

src/index.js.flow
test/flow.js

I saw that this PR: https://github.com/apollographql/react-apollo/pull/1126 is not being merged since its waiting on changes in apollo-client.
However, by updating the types to use the new React component typing semantics, I seem to be able to use these types properly.
Assuming this covers what's needed to upgrade (It's possible I could be missing something), this closes #1220 and closes #1105.
If there's more that needs to be updated, I'd be happy to look into updating those areas as well.

chore(flow): update flow types to flow-bin@0.56 semantics

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/mutations/lifecycle.test.tsx

Using another ApiClient with graphql container and mutation causes running of `this.updateQuery(nextProps);` which should not be executed for mutation from my understanding. 
Fixes already closed #812.

Do not update query after changing ApiClient

---

Changelog.md
package.json

Fixes [#1223](https://github.com/apollographql/react-apollo/issues/1223).

Removed redux from peer dependencies for v2

---

Changelog.md
src/types.ts

This is a companion PR for https://github.com/apollographql/react-apollo/pull/1143, which made the result fields partial in `ChildProps`. The same was needed in `OptionProps`, so I added it here.

Make OptionProps.data's TResult partial

---

Changelog.md
src/server.ts
test/react-web/server/index.test.tsx

React 16 now allows arrays to be returned from render. Update `walkTree` to
support this.
Closes #1158.

Support arrays in server-side rendering

---

Changelog.md
src/server.ts
test/react-web/server/index.test.tsx

Passing an updater function to `setState()` is something that React supports and people use this pattern. Fortunately, supporting that pattern in react-apollo's SSR mode is simple, so I added it and covered it with a test.

Support passing updater function to `setState` in SSR mode

---

Changelog.md
src/getDataFromTree.ts
test/react-web/server/index.test.tsx

initialize state to null if not when not set

---

Changelog.md
src/ApolloProvider.tsx

This fixes the typings of ApolloProvider.
>Rather than using the Cache type, which is defined in the TypeScript lib.dom.d.ts declaration file, for the generic parameter to ProviderProps in the ApolloProvider class, it may be more appropriate to use any to let the type flow through when the client is created. It may also be less confusing if the generic type parameter was renamed to something like TCache in the ProviderProps interface definition so it's not confused with the Cache type.
>
> I tested this change in the ApolloProvider.d.ts file and noticed the error went away and the client was properly typed as NormalizedCache when defining the cache as InMemoryCache.
Ref: https://github.com/apollographql/react-apollo/issues/1299

Fix <ApolloProvider/> typings

---

Changelog.md
src/graphql.tsx
test/react-web/client/graphql/queries/skip.test.tsx

#1181 seems to have not made it to react-apollo 2.0. This PR cherry-picks the change and updates the test to 2.0.

Forward-port #1181 to 2.0

---

README.md

This PR updates README.md from 1.0. usage closer to the 2.0. setup & usage from https://www.apollographql.com/docs/react/basics/setup.html.
The texts might need some rework though.

Move README.md closer to the 2.0. setup / usage

---

README.md

I added `graphql-tag` in README.md.
It's not working: `import { gql } from 'react-apollo';`

Added graphql-tag to README.md

---

src/getDataFromTree.ts
test/react-web/server/index.test.tsx

I have the case that occasionally a component may return an array with a `null` value in it. Unfortunately this breaks the tree walker and eventually our server side rendering:
> Cannot read property 'type' of undefined
>     at walkTree (/.../node_modules/react-apollo/react-apollo.umd.js:674:34)
From the React standpoint this should be totally fine: https://codesandbox.io/s/y0pl8pkwnx.
So in this PR I added a null check and tests to cover this case.

Skip null array items in `getDataFromTree`

---

README.md

The idea here is that adding a link to the apollo 1.x docs from the README:
1) Calls out up front that setup is different for apollo 1.x and apollo 2.x
2) Makes it easy to find the apollo 1.x docs

Add link to apollo 1.x docs in README

---

README.md

This PR removes the mention about `react-redux` functionality, as in 2.0 the `<ApolloProvider />` is not based on `react-redux`s `<Provider>` anymore.

docs(readme): Remove the mention about `react-redux` functionality

---

Changelog.md
src/getDataFromTree.ts
test/react-web/server/index.test.tsx

Recently #1355 was merged in to handle `null` elements. It's also possible, however, to return `undefined` elements and React is able to handle these just fine. `react-apollo` should support them as well.

Fix issue with SSR that has undefined array elements

---

src/graphql.tsx
test/react-web/client/graphql/queries/index.test.tsx

Originally opened as PR #1259, rebased by hand when Apollo-client 2.0 dropped.
Added a type generic to the graphql function named TGraphQLVariables.
It allows for specifying types that are required for the query that
should NOT be passed to the underlying component but are just used
for the GraphQL operation. The type is joined to the component's TProps
but not required on the passed in component.
Per apollographql/apollo-client#2198
This should not effect any current implementations as it defaults to {}.
Checklist:

feat(graphql): Added Variable generic type

---

Changelog.md
package.json
src/browser.ts
src/graphql.tsx

Rolls back on the changes made in #1344 due to breaking build

Rolled back on the lodash-es changes

---

test/react-web/client/graphql/queries/errors.test.tsx

`errors.test` is a frequent flaky offender on travis.  Increase the timeout to 250ms (hopefully that is enough) to ensure computation time to render component and gather count.

Make errors.test more lenient for travis

---

package.json
tslint.json

This PR makes prettier responsible for all formatting. This is something that is needed in PR #1448 where the conflicting formatting rules between prettier and tslint is causing issues.

Made prettier responsible for all formatting

---

Changelog.md
package.json
src/Query.tsx
tslint.json

Following #1449, attempt 2 at making prettier responsible for formatting.
I used a tool to remove all the lint rules that conflicted with prettier in the tslint.json. I also tested it on the file `Query.tsx` that is causing issues in #1448. 
This allowed me to remove `tslint-config-prettier` as a dependency.
Finally, I also updated the `pretty` script and the lint-staged script in the `package.json`.

Updated lint rule to make prettier responsible for formatting.

---

test/react-web/client/Query.test.js
test/react-web/client/graphql/queries/polling.test.tsx

After pulling master I observed that some tests related to polling functionality were failing intermittently. After a discussion with @rosskevin he pointed me in the direction of a timing workaround in `polling.test.tsx` which needed firming up.
Rather than relying on magic numbers for timing intervals it seems to be more sensible to take full control of advancing the timers ourselves. Fortunately [Jest provides an API for doing this](http://facebook.github.io/jest/docs/en/timer-mocks.html) and we can manually advance time as required. This should make the tests deterministic.
Note that `jest.runTimersToTime` has been renamed to `jest.advanceTimersByTime` in v22.0.0.
I think I may have another pass at this to rename some of the test variables as its actually the render count we are …

Fix for flaky polling tests

---

test/react-web/client/ApolloConsumer.test.tsx

`ApolloConsumer.test.js` is now `ApolloConsumer.test.tsx`

Switch ApolloConsumer.test to tsx

---

Changelog.md
package.json
rollup.config.js
rollup.test-utils.config.js
scripts/prepare-package.sh

Minify umd and ensure umd name consistency

Minify umd and ensure umd name consistency

---

package.json

I was looking at the test coverage to see where any weaknesses lie in terms of missing test cases - I noticed that the reported missed lines weren't mapped to the actual locations.
If we add the [`mapCoverage` Jest option](http://facebook.github.io/jest/docs/en/configuration.html#mapcoverage-boolean) the coverage output now matches up to the correct lines so that we can start to identify any missing test cases.
**Before**
**After**

Fix TypeScript test coverage

---

Changelog.md
src/Query.tsx
test/client/Query.test.tsx
test/client/__snapshots__/Query.test.tsx.snap

This PR removes the `variables` field in the result of the render prop in the `Query` component. The variable is already passed in the props of the component therefore there is no need to pass it in the render function.

Removed the variables from the render prop result in the Query.

---

src/index.js.flow

fixes two problems:
* def for `errorPolicy` option is missing
* the flow types required `options` to be a function returning the options,
but it appears `withApollo` can take a plain options object as well.

fix(index.js.flow): fix options and errorPolicy types

---

src/graphql.tsx

Check if error.stack contains error.message, and if not, append it to the error message
printed to the console.
This should fix error messages in Firefox and Safari.

Fix error messages for non-Chrome browsers.

---

src/Query.tsx
test/client/Query.test.tsx
test/client/__snapshots__/Query.test.tsx.snap

This PR ports the fix done in https://github.com/apollographql/react-apollo/pull/1531 to the `graphql` HoC into the new `Query` component. Also does the same for https://github.com/apollographql/react-apollo/issues/378.
Pinging @wdimiceli since I wrote the same method in `Query` slightly different and the test passed, so double checking with him. Particularly interested about the order of unsubscribing and subscribing to the new one, since I changed that to be able to reuse a method, and it seems it doesn't change the behavior.
Btw that looks like a "hacky" way to fix it, we should definitely find a way to fix this in apollo client (especially due to the lack of loading state in the fetch of the result after the error. See the test for more details).

Resuscribe after error in Query component

---

src/Query.tsx
test/client/Query.test.tsx
test/client/__snapshots__/Query.test.tsx.snap
test/server/getDataFromTree.test.tsx

This PR improves the types of `Query` for Typescript a bit. It adds variables as a parameter type, defaulting to an object of whatever. Also makes the `data` reflect the fact that it may not have information yet (in the initial load for example). Since it's better to check for null than for an empty object, I figured I'd change the API a bit and make `data` be either `TData` or undefined. Typescript works better in this case since it will refine the type after checking for its truthiness. Also I think it makes more sense than returning an empty object, since the null exception is going to be delayed until you try to access any nested property.
Anyway this is subject to improvement and discussion.

Improve types in Query component. Make data be undefined in initial load

---

Changelog.md
src/getDataFromTree.ts
test/server/getDataFromTree.test.tsx

Solves https://github.com/apollographql/react-apollo/issues/1595
@jbaxleyiii @leoasis

Fix React Component detection

---

Changelog.md
examples/typescript/package.json
examples/typescript/src/Character.tsx
src/ApolloConsumer.tsx
src/ApolloProvider.tsx
src/Query.tsx
src/getDataFromTree.ts
src/graphql.tsx
src/parser.ts
src/withApollo.tsx
test/client/graphql/shared-operations.test.tsx
test/test-utils/enzyme.ts
tsconfig.cjs.json
tsconfig.json

This PR rolls back the imports of non esm packages. This breaks the bundles as they try to import those and access their `default` property.

Rollback importing non esm packages

---

src/getDataFromTree.ts
test/server/getDataFromTree.test.tsx

The code in `getDataFromTree` which tries to build a composite Error of all encountered query errors does not work correctly. The final error thrown from the Promise will have the right message, but `queryErrors` will only have one item – that points to the composite error itself:
{ Error: 3 errors were thrown when executing your GraphQL queries.
at react-apollo.umd.js:763:19
queryErrors: [ [Circular] ] }
Upon investigating, the `catch` within `queries.map` was catching the composite error thrown within the recursive call to `getDataFromTree`. It's dutifully pushed onto the local `errors`, and then its `queryErrors` property is overwritten within the `Promise.all` `then` handler.
Using the two-argument form of `then` instead of a `then`/`catch` pair solves the issue.

Fix queryErrors in getDataFromTree

---

Changelog.md
package.json
src/Mutation.tsx
src/browser.ts
test/client/Mutation.test.tsx

This builds on the work of @excitement-engineer and fixes up the `any` types as well as returns the result from the mutation call

Mutation component

---

src/types.ts

Fix #1486 for the mutate options part (for query options, it's already solved).
The flow types were already correct.

[types] Add errorPolicy to mutate options in ts types, fix #1486

---

src/Mutation.tsx
src/index.js.flow
src/types.ts

fix #1647
Add ts and flow function type in refetchQueries mutate options.
I'm not familiar with flow, but the function type seems to be same as with typescript.

[types] Allow function for refetchQueries, fix #1647

---

src/Mutation.tsx
test/client/Mutation.test.tsx

The `<Mutation />` component did not allow the user to pass all the options as input to the mutate function passed in the render prop (only variables could be passed). This PR allows the user to pass all the options either through the props or as a parameter in the mutate function.
**Note, any option that is passed in mutate function overrides those passed in the props. This behaviour is similar to how the `graphql` HOC currently does it**.
This PR is required to implement the `withMutation` HOC in PR #1688.

allowed all options to be passed either in the props or as options in the mutate function

---

src/test-utils.tsx

This PR fixes the `../src` import problem for `ApolloProvider` in compiled `test-utils.js` detailed in #1720.

Fix ApolloProvider import (fixes #1720)

---

src/Query.tsx
src/test-utils.tsx
test/client/Query.test.tsx

Before, Query was passing options to `watchQuery` even if they were undefined. So, if we had { fetchQuery: undefined }, ApolloClient would not use the default because it is doing
Object.assign({}, defaults, { fetchPolicy: undefined }). So fetchPolicy would always be undefined
~* If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~
~* If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.~

fix(Query): allow using default options from ApolloClient

---

Changelog.md
src/Mutation.tsx
src/Query.tsx
src/queryRecycler.ts
src/types.ts
test/client/graphql/queries/index.test.tsx

With the refactor, I removed an untested path of passing a custom context to the link chain. Added smoke test and fixed

ensure context is passed to links

---

src/Mutation.tsx

When we are searching a query to refetch, we must take care to return the operation, if it exists, else we must return the original string.
The code in apollo-client does not handle a query equal to "undefined" but takes care of the string if properly forwarded to. See [the related code L254](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts).
How to reproduce the bug:
- provide a unknown query as a string in the mutation options. (ex: refetchQueries: ['test'])
- Run the mutation
- Instead of ignoring the query as expected, Apollo with throw an error: **"Uncaught TypeError: Cannot read property 'query' of undefined at QueryManager.js:143"**

Regression on 2.1.0-rc.3: refetchQueries throw errors on unknown queries

---

src/Subscriptions.tsx
src/subscription-hoc.tsx
test/client/Subscription.test.tsx

There is an inconsistency in the names of the props for the documents:
```
<Query query={} />
<Mutation mutation={} />
<Subscription query={} />
```
The name of the prop for the `Subscription` component is inconsistent with the others. Therefore, I propose that we call the prop `subscription` instead of `query`
```
<Subscription subscription={} />
```

Fixed inconsistency in naming of the prop for the subscription

---

src/Mutation.tsx
test/client/Mutation.test.tsx

Added a "called" field in the `MutationResult` prop returned in the render prop of the Mutation component. This field is true or false depending on whether the mutation has been called previously.
Adding this field ensures that the `MutationResult` object in the render prop is always defined which makes destructuring easier. In addition,  this will prevent confusion about the meaning of an undefined `MutationResult` in the render prop as mentioned by #1773.
Would love to hear some feedback regarding these changes. Does this improve the experience of using the `Mutation` component.

Added "called" prop to the Mutation component

---

README.md

I removed the full stack tutorial from the README because it is outdated and people are getting confused

Removing the tutorial from the README

---

src/browser.ts
src/withApollo.tsx

This exports the `WithApolloClient` type as a top-level export. Fixes #1816.
It also adds a default value for `withApollo`'s `TResult` parameter - it now defaults to `any`, for ease of use (e.g. if you're only using a mutation and don't care about the response [or the mutation always returns null] then there's no benefit in having to manually specify `any`).

Typing improvements for withApollo

---

src/Subscriptions.tsx
test/client/graphql/queries/reducer.test.tsx

With the new types, its harder to do simple spreading of data which is pretty common. I've added a test for it and will update the ts guide accordingly
This also moves the Observable to be from AL which is what AC actually uses and makes developing with npm linked apollo-client much easier

Common typing example

---

package-lock.json
src/Subscriptions.tsx
test/client/Subscription.test.tsx

I started investigating this when i noticed that my subscribed components were frequently missing messages that were definitely sent to the browser. On looking at the websocket frames, I noticed loads of resubscriptions occurring when no variables had actually changed:
If you look closely, you can see `stop` requests being sent immediately after data frames have been received. All these stops match up to UI re-renders. My theory is that upon every re-render, the subscription gets torn down and recreated. During this recreation, if a message arrives, it gets ignored because nothing is currently subscribed to it.
To verify i tried setting `shouldResubscribe` to false. This worked; I no longer missed any messages, and the crazy amount of resubscriptions disappeared (obviously):
As far as I …

Optimise resubscription checks and allow shouldResubscribe to be a function

---

src/Query.tsx
test/client/graphql/queries/__snapshots__/lifecycle.test.tsx.snap
test/client/graphql/queries/lifecycle.test.tsx

Adds a failing test and provides the fix for when refetch is called asynchronously from render. The component mounts, which starts the observable query subscription. Normally this would fetch data, causing a render, and the instance of refetch would be overridden with the force network. In cases of SSR, this second render does not occur. The refetch passed in the original render call needs to take this into account.

SSR enable asynchronous refetch call

---

package-lock.json
package.json

Bumped version of hoist-non-react-statics to 2.5.0 for compatibility with react 16.3.0
Fixes issue #1899

Bumped version of hoist-non-react-statics to 2.5.0

---

renovate.json

I'm raising this PR after noticing https://github.com/apollographql/react-apollo/pull/1921, which exhibited confusing pinning similar to that which I originally discovered in (`apollo-server`'s) https://github.com/apollographql/apollo-server/pull/954.
This changes Renovate to only pin the `devDependencies` in a `package.json` rather than all dependencies.
This is in the same spirit as the net result of (https://github.com/apollographql/apollo-server/commit/441cd9b838658132058945808097b97096bcb39f + https://github.com/apollographql/apollo-server/commit/db174a9b02354303ff845606e4c7bbfa03e58286) which were merged into `apollo-server`, as discussed in https://github.com/apollographql/apollo-server/pull/955#discussion_r180413510.

Update renovate.json to only pin `devDependencies`.

---

Changelog.md

This change is under the TypeScript and Flow only section, but is a change to the public API. People that aren't using flow or typescript might skip over this section and miss this important deprecation.

Move deprecation to correct section

---

src/test-utils.tsx

Currently using `pollInterval` leads to the following jest error message while testing:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests.
```
This is because when `stopPolling` is called, the actual polling timer is not getting deleted right away but after the interval completes. So we have to wait for one whole interval before jest can exist. See `fetchQueriesOnInterval` in the scheduler for the implementation details. 
This PR assumes that `MockedProvider` is only ever run with the intention that when it is unmounted every client op should also stop.
When `MockedProvider` is going to be unmounted, this PR adds the functionality to loop over all existing registered queries in …

Clear out scheduler on MockedProvider unmount

---

src/test-utils.tsx
test/test-utils.test.tsx

Fixes #2164 . Sorry for breaking the release :(.

Check if queryManager is set before accessing it

---

src/Query.tsx
src/query-hoc.tsx
test/client/Query.test.tsx
test/client/getDataFromTree.test.tsx

This reverts commit 2f15d9ff27574540ac4d873cc42a1ae64a6e663c.
#2313 introduced use of [Partial](http://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) for `TData` on a query result which makes all properties optional and is not correct or equal to the previous `TData | {}`.
@hwillson we should get a patch out asap as this is a **breaking change** in `2.2.0` for all users who are strongly typed.
/cc @tgriesser @donataswix

Revert "Use Partial<TData> rather than TData | {} (#2313)"

---

Changelog.md
src/Query.tsx
test/client/Query.test.tsx
test/client/getDataFromTree.test.tsx

https://github.com/apollographql/react-apollo/pull/1983 turned out to be breaking for many Typescript users. Rolling back those changes, and we'll find another way to get something similar in place.
Fixes https://github.com/apollographql/react-apollo/issues/2424.

Revert 27cc028 (https://github.com/apollographql/react-apollo/pull/1983)

---

test/client/Query.test.tsx

#1983 introduced breaking changes that were missed by the current test suite. These changes were  rolled back in #2432, but the test changes in this PR should help prevent this same issue from happening again.
Reference: #2424

Test changes to ensure type guard isn't needed on result `data`

---

src/browser.ts
typings/lodash_flow-right.ts

fix lodash typings

---

Changelog.md
package-lock.json
package.json
src/parser.ts

- Update dev dep to `graphql` 14.0.2
- Update `@types/graphql` to 14.0.1
- Add missing `graphql` peer dep, covering 0.11 to 14

Update to `graphql@14`

---

Changelog.md
src/Query.tsx
test/client/Mutation.test.tsx

Fixes #2421
This fixes an issue where any update to the query variables/props aren't reflected in the context operations map, so when a mutation triggers a refetchQueries by name, it does not use the correct variables. This fixes that by making certain the operations map is correctly set on all updateQuery calls.

Fixes refetchQueries with string using wrong variables

---

package-lock.json
package.json

Moved `lodash.isequal` to dependencies as required by `MockLink` / `MockedProvider`, fixes #2448
Caused by https://github.com/apollographql/react-apollo/commit/4eebfdc0f1614583ed877583285551ed4c39ddba
cc @hwillson

Moved lodash.isequal to dependencies

---

Changelog.md
src/Query.tsx

This PR is a followup to https://github.com/apollographql/react-apollo/pull/2003
While the above mentioned PR set the `loading` status on the partial merged data, clients using the `networkStatus` to infer loading state were breaking still. This fixes `networkStatus` to reflect the loading state correctly for partial refetching, thus patching that hole.
Acknowledgements:
Thanks to @vafada for his help in investigating this
Edit: Rebased on master

Patch networkStatus along with loading attribute

---

.github/PULL_REQUEST_TEMPLATE.md

Removing all mentions of labelling from this repos custom issue/PR templates (since we're no longer using Apollo Bot).

Remove labels from GH templates since we're disabling Apollo Bot

---

Changelog.md
package-lock.json
package.json
src/getDataFromTree.ts
src/renderToStringWithData.ts

Supersedes #2593.
Should fix #2592.
By pushing the `react-dom/server` import down into the relevant functions that need it, we can avoid unconditionally importing that dependency tree, which helps in environments like React Native where `react-dom/server` either doesn't work or seems undesirable (see discussion in #2592).
Since the React Native bundler will still try to traverse the `require("react-dom/server")` dependencies, it's important to prune that dependency with a
```json
"react-native": {
"react-dom/server": false
}
```
section in `react-apollo/package.json`. Note that this does not prevent React Native apps from using `getMarkupFromTree` with an appropriate `renderFunction`; it simply prevents React Native's bundler from bundling the `react-dom/server` dependency just because …

Remove top-level react-dom/server import to fix #2592.

---

Changelog.md
package-lock.json
package.json

This PR includes the following React dependency changes:
- Drop `react` 14.x support, since the 14.x release line is 2 years old now, and `react-apollo` is no longer tested against it.
- Add `react-dom` as a peer dependency (since it's used by `getDataFromTree` and `renderToStringWithData`).

Drop support for react 14, and list react-dom as a peer dep

---

src/Mutation.tsx
test/client/Mutation.test.tsx

Closes #2293 [(Query onCompleted not invoked)](https://github.com/apollographql/react-apollo/issues/2293)
When passing both `onCompleted` and `refetchQueries` to a `Mutation` that un-mounts as a result of `refetchQueries`, `onCompleted` will never be called.
Consider the following example:
A logout button that invokes a mutation, which re-fetches a query to propagate this change to the rest of the app (e.g. removing references to the currently logged-in user).
On that mutation, we have an `onCompleted` to redirect to the login page after both _a successful logout mutation_ AND _a successful refetch_ .
With the current implementation, `onCompleted` will never be called because as soon as `refetchQueries` is finished, the logout mutation will unmount and the redirect will never happen. …

Invoke onCompleted/onError even if Mutiation unmounts

---

Changelog.md
examples/typescript/src/Character.tsx

Extending the Query component as a class means that the compiled code
generates an extra object. By using the raw Query component directly
with generics, we avoid this extra artifact and simplify the code

TS example: replace class extension of Query component

---

package-lock.json
package.json
src/test-utils.tsx

This `stop` method was introduced in apollo-client@2.4.12: https://github.com/apollographql/apollo-client/pull/4336
Credit to @danilobuerger for suggesting we hide the details of stopping the `MockedProvider` client using a new `ApolloClient` method: https://apollographql.slack.com/archives/C2FERSTGC/p1547849096341900
The `stop` method would have made https://github.com/apollographql/react-apollo/issues/2738 a non-issue, since we could easily change the implementation of `stop` without affecting its consumers.

Use ApolloClient#stop to clean up MockedProvider client.

---

src/Query.tsx
src/getDataFromTree.ts
test/client/getDataFromTree.test.tsx

Closes #2680
Closes #2134
Closes #1972
Closes #1781 
Closes #615
This change tracks the original observable used during a SSR. When the Query component is recreated due to a Query's promise resolving, then the original queryId used to track the response error is lost. By tracking the original observable, the newly instantiated Query component can reference the original observable to retrieve the actual result. This makes the feature work like the documentation states, which allows server side rendered components to properly handle errors rather than throwing exceptions.

fix: When doing a SSR with errorPolicy='all', then error should not be lost

---

.gitignore
Changelog.md
jest.browser.umd.config.js
jest.server.umd.config.js
package-lock.json
package.json
rollup.config.js
scripts/prepare-package.sh
src/Mutation.tsx
src/Query.tsx
src/Subscriptions.tsx
src/browser.ts
src/queryRecycler.ts
src/utils/flowRight.ts
src/utils/shallowEqual.ts
test/client/getDataFromTree.test.tsx
test/client/graphql/shared-operations.test.tsx
test/client/utils/flowRight.test.tsx
tsconfig.cjs.json
tsconfig.json

Part of issue #2743, whose description previously appeared here.

[WIP] Reduce bundle size.

---

COLLABORATORS.md

As we bring on new collaborators, it's important that we have a small and direct list of guidelines that collaborators can follow. This list should be kept as small as possible so it's easy to consume, and easy to remember, until the outlined steps become muscle memory for collaborators.

Add collaborator guidelines

---

package-lock.json
package.json

When testing new `react-apollo` changes out (during core development), it can be useful to `npm link` `react-apollo` into a test app. After the link is in place, the `npm run watch` script can be used to compile typescript file changes, in watch mode. So while working on the `react-apollo` codebase, .ts file changes will be picked up automatically, compiled, and because of the `npm link`, the test app will recognize that there have been changes made to `react-apollo` and re-run with the updated version.
Unfortunately, `npm run watch` doesn’t currently work as it’s missing the additional post compilation steps that `npm run compile` leverages via `postcompile`. This mean that `npm run watch` isn’t calling `rollup` and generating the associated ESM/UMD bundles. So when typescript changes …

Make sure  `npm run watch` builds ESM/UMD bundles

---

Changelog.md
src/test-links.ts
test/test-utils.test.tsx

The `result` property of a `MockedResponse` is currently restricted to being a pre-configured fixed value. Allowing results to be calculated/returned from a function instead of being pre-configured, opens up new test verification paths, that can be useful when using `MockedProvider`.
This PR adjusts `MockedResponse`’s `result` such that if a function is set for its value, that function will be fired and its result will be passed to the Observable matching the incoming mocked `request`.
Fixes https://github.com/apollographql/apollo-feature-requests/issues/84.

Allow `MockedResponse` results to be returned from a function

---

package-lock.json
package.json
src/Mutation.tsx
src/Query.tsx
src/hoc-utils.tsx
src/mutation-hoc.tsx
src/query-hoc.tsx
src/subscription-hoc.tsx
src/test-links.ts
src/test-utils.tsx
test/client/Query.test.tsx
test/client/graphql/queries/index.test.tsx
test/client/graphql/queries/lifecycle.test.tsx
test/client/graphql/queries/polling.test.tsx

This PR makes a few odds/ends changes to React Apollo, to better align it with the upcoming Apollo Client 2.5.0 release and local state. It includes:
- Updating the `apollo-*` deps to use the `beta` versions from Apollo Client (for `react-apollo@beta` testing)
- Updates to the Apollo Link dependency and associated Typescript changes
- Disabling HOC prop variable validation, since it won't work with `@client @export` (see the description in https://github.com/apollographql/react-apollo/commit/cce3316e7e3ed65f554346fe59d6c320d6b695da for more details)
- Prevent React Apollo's `MockedProvider` from using `@client` fields in mocked out links, since `@client` fields are now local (and shouldn't be included in links).
- Start tracking the full last received query result in the `Query` …

Changes to accommodate AC's integrated local state handling

---

Changelog.md
src/test-utils.tsx

After the changes in https://github.com/apollographql/apollo-client/pull/4499, when `MockedProvider` is currently used it doesn't have any `resolvers` set. This means `@client` directives are passed into the link chain. Since we don't currently allow people to modify the link chain that `MockedProvider` uses, it's safe to assume people won't want this behaviour, as they can't test things like `apollo-link-state` this way. This PR sets a default `resolvers` value of `{}` to enable AC 2.5's new local state handling, and opens the door for passing custom resolvers into the `MockedProvider` via props.
Helps with https://github.com/apollographql/fullstack-tutorial/pull/73.

Allow resolvers to be passed into `MockedProvider` and set a default

---

Changelog.md
src/types.ts
src/walkTree.ts

When we stopped reexporting everything from `walkTree.ts` as part of #2533, we also stopped exporting the `Context` type that it uses.
Moving the declaration and export of `Context` from `walkTree.ts` to `types.ts` restores the ability to do
```ts
import { Context } from "react-apollo"
```
which should fix #2824.

Export Context type from types.ts instead of walkTree.ts.

---

examples/rollup/.gitignore
examples/rollup/index.html
examples/rollup/main.js
examples/rollup/package-lock.json
examples/rollup/package.json
examples/rollup/rollup.config.js

The goal of this application is to get a precise, real-world measurement of the total bundle footprint of essential Apollo Client and React Apollo packages, using a modern bundler, including the weight of dependencies (excluding `react` and `react-dom`), but also taking into account the overlap between shared dependencies, which is not possible with per-package tools like https://bundlephobia.com/result?p=apollo-client@2.5.1.
If you run
```bash
cd react-apollo/examples/rollup
npm install
npm run analyze
```
in this application, you'll see a breakdown of everything in the bundle that we think should be attributed to using Apollo Client and React Apollo. The current total stands at about 143KB (minified but *not* compressed with gzip, since that's how `source-map-explorer` works). After …

Add a basic example app bundled with Rollup.

---

package.json
rollup.config.js
src/Query.tsx

Part of our ongoing effort to rein in bundle sizes: https://github.com/apollographql/react-apollo/issues/2743
Although the `bundlesize` check will show a reduction in the size of `react-apollo` itself, the most accurate measurement of these improvements is [the `examples/rollup` app](https://github.com/apollographql/react-apollo/tree/master/examples/rollup), introduced by #2839.
That said, the numbers are pretty close, because the `tslib` package is now shared by so many Apollo packages that it's effectively free from the perspective of any single package.

Bundle reductions inspired by examples/rollup app.

---

test/client/graphql/queries/loading.test.tsx
test/client/graphql/queries/skip.test.tsx

This PR is preparation for https://github.com/apollographql/apollo-client/pull/4576, which introduces some slight changes in the timing of link requests, resulting in query deduplication in some new (or just more frequent) cases.
While deduplication should be harmless/beneficial in most real applications, it can affect the number of requests made to the underlying `ApolloLink` in ways that some `react-apollo` tests do not expect. To make those tests more reliable, it seems best to disable query deduplication by passing `queryDeduplication: false` to the `ApolloClient` constructor used by the test.
I would be more worried about this change if the tests were reliably failing, but the `loading.test.tsx` test was passing occasionally without this change, and the rate of success could be …

Disable queryDeduplication in some flaky tests.

---

Changelog.md
src/ApolloContext.ts
src/react-apollo.cjs.ts
src/test-utils.tsx

When running `MockedProvider` tests from a CLI or CI, those tests are run using the CommonJS bundled version of React Apollo (`react-apollo.cjs.js`). The `test-utils` themselves however, like `MockedProvider`, are not included in the production `react-apollo.cjs.js` bundle, to help keep the prod bundle size down. To use `MockedProvider`, it must be accessed using a nested/direct import like:
```js
import { MockedProvider } from "react-apollo/test-utils";
```
Unfortunately, this nested import means `MockedProvider` is loaded outside of the `react-apollo.cjs.js` bundle, which means it requires and uses its own versions of other supporting React Apollo files. This causes problems in areas like using React's Context API. Both `MockedProvider` and the component's it's attempting to test create …

Force `test-utils` to use the CJS version of React Apollo

---

Changelog.md
src/Query.tsx
test/client/Query.test.tsx

This PR makes sure `no-cache` (`fetchPolicy`) loaded data is preserved when a components tree is re-rendered.
Fixes #2870.

Persist `no-cache` Query loaded data when re-rendering

---

Changelog.md
package-lock.json
package.json
src/Query.tsx
src/queryRecycler.ts
src/types.ts
test/__snapshots__/test-utils.test.tsx.snap
test/client/Query.test.tsx
test/client/graphql/queries/errors.test.tsx
test/client/graphql/queries/index.test.tsx

Apollo Client 2.6 integration work.

Apollo Client 2.6 integration work

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question-discussion.md
CONTRIBUTING.md

Adjust the new issue page to show multiple options, making sure it's clear that feature requests should be opened in the Apollo FR repo.

New issue template changes

---

packages/all/package.json
packages/common/package.json
packages/components/package.json
packages/hoc/package.json
packages/hooks/package.json
packages/testing/package.json

RA 3 is dependent on changes made in `apollo-client` 2.6.3.
Fixes #3148.

Bump all `apollo-client` peer deps

---

Changelog.md
src/Query.tsx

To fix issue #3090, the `ObservableQuery.resetQueryStoreErrors` method was introduced in `apollo-client` 2.6.3. While `apollo-client` 2.6.3 is a peer dep of the latest version of `react-apollo` (2.5.7), people who can't update their version of `apollo-client` to >= 2.6.3 are running into issues when updating to the latest version of `react-apollo`, since `ObservableQuery.resetQueryStoreErrors` isn't available to them. Since we can't enforce the version of `apollo-client` people are using, this commit adjusts the `Query` component to only use `resetQueryStoreErrors` if it's available. If it isn't, it will call into the `ObservableQuery`'s private API to do the same things as `resetQueryStoreErrors`. This is a hack, but it is temporary as `react-apollo` is launching soon, and will enforce a …

Conditionally use AC's `ObservableQuery.resetQueryStoreErrors`

---

package.json
packages/hooks/src/__tests__/useSubscription.test.tsx
packages/hooks/src/data/MutationData.ts
packages/hooks/src/data/OperationData.ts
packages/hooks/src/data/QueryData.ts
packages/hooks/src/data/SubscriptionData.ts
packages/hooks/src/useSubscription.ts

The `useSubscription` Hook isn't properly restting/removing the internal `ObservableQuery` instance it uses, when it's no longer needed. This means that the subscription used by the hook is never properly shut down, leading to unnecessary network communication. This PR ensures that the `useSubscription` internals are properly cleansed when the component wrapping the hook is unmounted.
Fixes #3160.

Make sure `useSubscription` cleans up when done

---

config/rollup.config.js
examples/hooks/client/src/index.tsx
package-lock.json
package.json
packages/hooks/package.json
packages/hooks/src/data/MutationData.ts
packages/hooks/src/data/OperationData.ts
packages/hooks/src/data/QueryData.ts
packages/hooks/src/data/SubscriptionData.ts

After talking with @hwillson, this seems like a pretty easy swap to thin out the package by quite a lot! Let's see what bundlesize says after its done though...

remove apollo-utilities in favor of just the isEqual needs from the shared root

---

package-lock.json
packages/components/package.json
packages/hoc/package.json

This should have been in the `hoc` package, instead of `components`.
Fixes #3173.

Move the `hoist-non-react-statics` dep to the proper package

---

examples/hooks/client/package.json
examples/hooks/client/src/NewRocketForm.tsx
package.json
packages/components/src/Mutation.tsx
packages/hooks/README.md
packages/hooks/src/__tests__/useMutation.test.tsx
packages/hooks/src/data/MutationData.ts
packages/hooks/src/types.ts
packages/hooks/src/useMutation.ts

This commit re-arranges the `useMutation` result tuple such that the mutation result is in the first position, with the mutation function in the second position. The intent of this change is to bring the `useMutation` Hook more in-line with how the React Core handles its Hook results (e.g. `useState`, `useReducer`).
**This is a breaking change, but since we're in beta hopefully that's okay.** To help lessen the blow a bit this commit includes changes to display a `console.warn` message describing the API changes. This message will be removed before the final version of React Apollo 3 is published.
Fixes #3189.

Adjust `useMutation` result tuple to be more inline with React Core

---

packages/components/src/__tests__/client/ApolloProvider.test.tsx

Quick test to show that one `ApolloProvider` instance can be used across multiple `@apollo/react-X` packages, and have each one of them share the same context.
Validates #3193.

Validate that one `ApolloProvider` can be used across packages

---

examples/hooks/client/src/NewRocketForm.tsx
packages/components/src/Mutation.tsx
packages/hooks/README.md
packages/hooks/src/__tests__/useMutation.test.tsx
packages/hooks/src/data/MutationData.ts
packages/hooks/src/types.ts
packages/hooks/src/useMutation.ts

While the changes requested in #3189 and implemented in #3199 seemed like a good idea, we no longer think it makes sense for React Apollo to align its hooks API with React's core hooks API. In `useMutation`'s case, the mutation function will almost always be called, whereas the results aren't necessarily used. For this reason it makes sense to keep the mutation function in the first position of the result tuple.

Switch back to the mutation function in first tuple position

---

packages/common/src/types/types.ts
packages/components/src/Mutation.tsx
packages/hoc/src/mutation-hoc.tsx
packages/hooks/README.md

Apollo Client was updated a while back to allow both objects and functions as an `optimisticResponse` option. This commit updates React Apollo accordingly.
Fixes #3248.

Fix incorrect `optimisticResponse` types

---

packages/hooks/src/__tests__/useQuery.test.tsx

Extra tests to help verify that `GraphQLError`'s included when mocking requests are sent back in `useQuery` results properly.
Fixes #3233.

Verify GraphQLError's are being handled properly

---

packages/hooks/src/__tests__/useMutation.test.tsx

Optimistic response handling is already verified through the `Mutation` component test suite (which ultimately calls into `useMutation`), but we'll add a `useMutation` specific test to help validate #3217.
Fixes #3217.

Add `useMutation` optimistic response test

---

packages/components/src/Query.tsx
packages/hooks/src/data/QueryData.ts

When new data or errors are reported back through the `ObservableQuery` subscription, `updateCurrentData` is called to trigger a forced update of the parent component (to reflect the new component state). Before triggering the forced update however, `updateCurrentData` first checks to see if the component is mounted (since we don't want to try to trigger a forced update on a copmonent that isn't mounted). Unfortunately, a component isn't marked as being mounted until the `afterExecute` method is called via a `useEffect`. Under certain circumstances it's possible for the `ObservableQuery` subscription to be initialized and get data back before the `useEffect` has fired and marked the component as mounted. This means when `updateCurrentData` is triggered with valid updates, they're …

Prevent ObservableQuery component updates from being blocked

---

Changelog.md
package.json
packages/all/src/index.ts

Oops! 😳
Fixes https://github.com/apollographql/react-apollo/issues/3319.

Add missing `useLazyQuery` export to `react-apollo`

---

Changelog.md

compose gets removed in 3.0.0. This suggestion would have been helpful to me when I upgraded.

Add suggestion to Changelog.md for removal of compose

---

Changelog.md
packages/hooks/src/__tests__/useMutation.test.tsx
packages/hooks/src/types.ts

`void` is left over from pre-launch mutate function experiments, and is causing grief when attempting to destructure promise-returned data from the `useMutation` mutate function. Goodbye `void`!
Fixes #3322.

Remove `void` from possible `MutationTuple` promise generic

---

Changelog.md
packages/testing/src/mocks/MockedProvider.tsx
packages/testing/src/mocks/types.ts

These were available in `react-apollo@2`, and there isn't any reason not to expose them.
Fixes #3336.

Export `MockedProviderProps` and `MockedProviderState`

---

Changelog.md
packages/hooks/src/__tests__/useQuery.test.tsx

Issue #3295 demonstrates a problem where errors aren't maintained on re-renders, when they should still be available. This issue was fixed by PR #3339, but this commit will add an extra test to verify that the issue is indeed fixed.
Fixes #3295.

Add test to verify error is persisted on re-render, when appropriate

---

Changelog.md
packages/all/package.json
packages/common/package.json
packages/components/package.json
packages/components/src/__tests__/client/Query.test.tsx
packages/components/src/__tests__/client/__snapshots__/Query.test.tsx.snap
packages/hoc/package.json
packages/hooks/package.json
packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts
packages/ssr/package.json
packages/ssr/src/__tests__/useQuery.test.tsx
packages/testing/package.json

React Apollo returns an empty object for the initial `data` value, that is returned when performing a query. There a long history behind why this is the case, but this single issue has caused a lot of frustration over the past long while due to the following:
- `{}` is not the same as having no data; it's an object, not nothing. If there is no data, we shouldn't pretend there is.
- Setting `data` to `{}` isn't followed in all cases; e.g. when errors occur, during parts of SSR, when skipping, etc. This leads to developers having to know when to expect `{}` and when to expect `undefined`.
- Forcing no data situations to be empty objects can go against application schemas that enforce a value and don't allow empty objects.
This PR adjusts React Apollo's default query `data` state to be …

Change the default query `data` state from `{}` to `undefined`

---

Changelog.md
package.json
packages/hoc/src/__tests__/queries/skip.test.tsx
packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts

Prior to this PR, when `notifyOnNetworkStatusChange` is true calls to `fetchMore` do not wait for `updateQuery` to finish, before triggering a re-render. This means that after a `fetchMore` call, components will flip to `loading: true`, then `loading: false`,  then un-necessarily re-render once more as `loading: false` with the result from `updateQuery`. This commit adds a check to see if `fetchMore` has been called and then holds off on re-rendering the `loading: false` state, until `updateQuery` has fully finished. 
Fixes #3333

Fix problematic `fetchMore` `notifyOnNetworkStatusChange` renders

---

Changelog.md
package.json
packages/hooks/src/__tests__/useMutation.test.tsx
packages/hooks/src/data/MutationData.ts

This fixes #3366 
According to the [docs](https://www.apollographql.com/docs/react/api/react-components/#mutation) the client should be in the result. This updates the result to have the client on MutationData added to the result. If the client is undefined, it will refresh it and add it on there.

add client to the mutation result

---

Changelog.md
packages/common/src/types/types.ts

The resolved value of the returned `Promise` from a `MutationFunction` cannot be `void`.
Fixes #3432.

Remove `void` from `MutationFunction` Promise return type

---

Changelog.md
packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts
packages/hooks/src/utils/useBaseQuery.ts

This PR tweaks the dependencies that are watched to decide if `afterExecute` should be called (which triggers `onCompleted`), in `useQuery`. This helps prevent extra and un-necessary repeated calls to `onCompleted`, during a single query request-response cycle.

Prevent duplicate `onCompleted` calls during query execution

---

packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts

This PR will fix 'unchanging loading state' when an error, the _same_ with previous error, is occurred after `refetch` (described in #3395).  
\# *'same'* depends on `@wry/equality` implementation.
`previousData.result.loading` in `QueryData` should be `true` just before the first `error` handler called for any fetch/refetch, so this PR checks its value, and always calls `forceUpdate` if the value is `true`.  
(related PR: #3339)
After:
1. some fetch has triggered with `notifyOnNetworkStatusChange: true`
2. `loading` changes to true
3. an error occurrs for the fetch
4. `loading` changes to false and the error data can be used
5. call `refetch`
6. `loading` changes to true
7. an error occurrs for the refetch (the error message the same with the error occurred in step 3)
8. `loading` …

fix: force update just after loading done with error even if the error is unchanged

---

Changelog.md

The change in the return type of the data prop should be highlighted as a breaking change, it'll be a bc if someone is rendering a component like this: 
`<span>{data.queryResult && data.queryResult.total}</span>`
I think it'll be clearer for the devs that will be checking the changelog after they see that their app broke after upgrading the version.
Anyways gw guys, ❤️  the apollo stack, cheers.

Highlight the breaking change in the data prop

---

Changelog.md
package.json
packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts

Polling is automatically stopped when a component is unmounted, so it isn't necessary to call `stopPolling` during component cleanup. If it is called though, we don't want to throw an exception, so these changes make it (and `startPolling`) a no-op if component cleanup has already happened.
Fixes #3482

Make `stopPolling` / `startPolling` a no-op after unmount

---

Changelog.md
packages/hooks/src/data/QueryData.ts

Fix runtime error with fast-refresh

---

Changelog.md
packages/all/src/index.ts
packages/hoc/src/types.ts

These were accidentally removed during the 3.0 refactor.
Fixes #3421

Bring the `ChildDataProps` and `ChildMutateProps` types back

---

Changelog.md
packages/hooks/src/__tests__/useLazyQuery.test.tsx
packages/hooks/src/utils/useBaseQuery.ts

Make sure `onCompleted` is called each time a `useLazyQuery` based query completes, after the execution function is called.
Fixes #3488

Call `onCompleted` each time `useLazyQuery` executes

---

packages/testing/src/mocks/mockLink.ts

This PR attempts to fix issue #3455 by splittting destructuring result after newData is retrieved:
```diff
-    const { result, error, delay, newData } = response;
+    const { newData } = response;
if (newData) {
response.result = newData();
this.mockedResponsesByKey[key].push(response);
}
+    const { result, error, delay } = response;
+
if (!result && !error) {
throw new Error(
`Mocked response should contain either result or error: ${key}`
```

Fix newData raising error per #3455 issue

---

Changelog.md
packages/hooks/src/__tests__/useQuery.test.tsx
packages/hooks/src/data/QueryData.ts

Solves #3468
Although #3433 has improved performance by reducing the number of renders in pagination, it only works when the fetchMore function returns a new list.
If we reached to the end of the list, the fetchMore function returns the same length of result, which is determined as equal by the [@wryware/equality library](https://github.com/benjamn/wryware/blob/50e7d6181b0b937ad54b543118e823ad98e2bca9/packages/equality/src/equality.ts#L40) we currently use. Therefore, reading the last page of the list remains `networkStatus` to `NetworkStatus.fetchMore`.
I think [apollo-client](https://github.com/apollographql/apollo-client) needs to send the updated fetchMore result and the changed networkStatus at once.

Fix an error that the networkStatus did not change to ready at the end of pagination

---

Changelog.md
packages/components/src/__tests__/client/Mutation.test.tsx
packages/components/src/__tests__/client/Query.test.tsx
packages/hoc/src/__tests__/mutations/queries.test.tsx
packages/hoc/src/__tests__/queries/errors.test.tsx
packages/hoc/src/__tests__/queries/loading.test.tsx
packages/hoc/src/__tests__/queries/skip.test.tsx
packages/hooks/src/data/QueryData.ts
packages/hooks/src/types.ts
packages/hooks/src/utils/useBaseQuery.ts
packages/ssr/src/__tests__/useLazyQuery.test.tsx
packages/ssr/src/__tests__/useQuery.test.tsx

As of version 16.13.0, React logs a warning when a function component is updated during another component's render phase (facebook/react#17099). PR #3902 addresses some of this, but doesn't quite catch all scenarios where this can occur. These changes take things further, ensuring that React Apollo components can't force update during a render phase.
Fixes #3863

Avoid React 16.13.0 update during render warning
