ambient.d.ts, src/connect.tsx, typings.json
This massively drops the file size of this project
=> Thin library size

package.json, src/connect.tsx, test/connect.tsx
This PR brings in changing of the loading status when a query is refetched, or when a mutation is called
=> Lifecycle for apollo store

src/connect.tsx, test/connect.tsx
=> correctly rerender on passed prop changes

src/connect.tsx
=> correctly pass through errors

README.md
Per discussion here https://github.com/apollostack/docs/pull/25
=> Clear readme in favor of docs site

src/connect.tsx
Per: https://github.com/apollostack/apollo-client/pull/133
This will need a test added when I refactor all of the tests.
=> pass through refetch args

src/connect.tsx, test/connect/queries.tsx
This matches the functionality from apollo-client here https://github.com/apollostack/apollo-client/pull/178
=> Return promise on refetch

Changelog.md, src/connect.tsx
=> don't set the loading state to false if forceFetch is true

Changelog.md, package.json, src/connect.tsx, test/client/connect/mutations.tsx, test/client/connect/props.tsx, test/client/connect/queries.tsx, test/server/index.tsx
=> fix overrendering of components

Changelog.md, package.json, src/connect.tsx
=> fix react-native issue

Changelog.md, package.json, src/graphql.tsx, test/react-web/client/graphql/fragments.tsx, test/react-web/client/graphql/queries.tsx, test/react-web/client/graphql/shared-operations.tsx, test/react-web/server/index.tsx
=> Fix SSR with mutations, fix mixing initial props methods, allow object for options

Changelog.md, src/server.ts, test/react-web/server/index.tsx
=> fix react warnings and change renderToString api

src/graphql.tsx, test/react-web/client/graphql/queries.tsx, test/react-web/client/graphql/shared-operations.tsx, test/react-web/client/libraries/redux.tsx
=> Fixes loading state true for skipped queries

Changelog.md, package.json, src/graphql.tsx, test/react-web/client/graphql/queries.tsx
=> added update query

test/react-web/client/graphql/queries.tsx
See https://github.com/apollostack/react-apollo/issues/188#issuecomment-244825318
=> Added test for #188

Changelog.md, package.json, src/graphql.tsx, test/react-web/client/graphql/queries.tsx
Failing test. If it passes, it will fix #202
=> UpdateQuery in componentWillMount

Changelog.md, package.json, src/graphql.tsx, test/react-web/client/graphql/queries.tsx
In order to better support subscriptions!
=> fix updateQuery early usage

Changelog.md, src/graphql.tsx
=> remove nested imports for apollo-client

package.json, test/react-web/client/libraries/redux-1.test.tsx, test/react-web/client/libraries/redux-2.test.tsx
I happened to be looking at this so I figured I should check it works with the new v6 API.
PS nice new tests!
=> Update `redux-form` used in tests to v6

package.json, test/react-web/client/graphql/queries-1.test.tsx
> Right now this is a test to try to replicate #252
=> added unsubscribe test

Changelog.md, package.json
=> 0.5.9 release

test/react-web/client/graphql/queries-1.test.tsx, test/react-web/client/graphql/shared-operations-1.test.tsx
=> Use `fail(err)` rather than `done(err)`

package.json, src/graphql.tsx, test/react-web/client/graphql/queries-1.test.tsx
=> Add subscribeToMore to passthrough methods

src/graphql.tsx, test/react-web/client/graphql/fragments.test.tsx
=> Fix nested fragment arrays

package.json, yarn.lock
Fix as suggested by @vlasenko on Slack.
=> Fix issues w/ react@15.4 & jest-react-native

Changelog.md, src/graphql.tsx, test/react-web/client/graphql/queries-1.test.tsx
=> Feature: Add networkStatus to props of the connected components

Changelog.md, src/graphql.tsx, src/server.ts, test/react-web/server/index.test.tsx, yarn.lock
Fixes issue with Redux's `connect` hoisting `fetchData` statically.
See #350
=> Use instance.fetchData rather than a static method.

.npmignore, .travis.yml, Changelog.md, package.json
=> update build script

src/graphql.tsx
Fixes https://github.com/apollostack/react-apollo/issues/378
TODO:
=> Fix GraphQL error passing to components

Changelog.md, package.json
=> add react-dom as peer depency

Changelog.md, package.json, yarn.lock
Fixes https://github.com/apollographql/react-apollo/issues/469
=> Remove chai types

Changelog.md, package.json
=> Update apollo-client dependency

package.json, test/react-web/client/graphql/queries.test.tsx
Had to fix `fetchMoreResult` due to recent breaking change.
=> Greenkeeper/apollo client 1.0.0 rc.5

Changelog.md, src/ApolloProvider.tsx, src/graphql.tsx, test/react-web/client/ApolloProvider.test.tsx
=> ApolloProvider: don't override store if not passed

package.json, test/react-web/client/graphql/queries.test.tsx
=> Apollo Client 1.0 rc.7

package.json, test/react-web/client/ApolloProvider.test.tsx
=> chore(package): update apollo-client to version 1.0.0-rc.9

package.json
=> chore(package): update apollo-client to version 1.0.2

Changelog.md, src/graphql.tsx, test/react-web/client/ApolloProvider.test.tsx, test/react-web/client/graphql/queries.test.tsx, test/react-web/client/graphql/shared-operations.test.tsx
Originally proposed in #653, but modified to support other context changes going down
TODO:
=> shouldComponentUpdate perf

src/parser.ts
=> typo: muations => mutations

src/graphql.tsx, src/server.ts
Hi!
I sent a very small one letter typo fix. Do the TODO items below still apply, namely updating the CHANGELOG?
TODO:
=> Fix typo in `walkTree` comment

test/react-web/client/graphql/queries/errors.test.tsx
=> increase setTimeout for intermittent test failre

Changelog.md, examples/create-react-app/src/Pokemon.test.js, package.json, rollup.test-utils.config.js, test/react-web/client/graphql/queries/errors.test.tsx
=> Fix test utils

.github/stale.yml
=> Fix typos in stale.yml

src/graphql.tsx
Fixes some failings with typescript
=> Typescript updates

Changelog.md, package.json, src/browser.ts
=> export types

Changelog.md, package.json, src/index.js.flow, test/flow.js
This PR updates `DefaultChildProps` to be `ChildProps` for the flow types to match the TS signatures
=> Flow to ts

src/index.js.flow
Fixes: https://github.com/apollographql/react-apollo/issues/931
See each commit message for description!
=> Flow fixes

Changelog.md, package.json
`1.4.11` was deployed without cd into the built files so it was a broken build. It is fixed with 1.4.12 (already out)
=> Fix issue from broken deploy

Changelog.md, package.json
=> version bump

Changelog.md, src/shallowEqual.ts, test/shallowEqual.test.ts
=> false when one of shallowEqual arguments is falsy value

package.json, src/index.js.flow, test/flow.js
Until apollo-client is updated, this PR will have flow errors 👎  I'll update that today and then update this to that version and release
=> Revert "Upgraded to 0.54.1 Flow"

README.md
This is just a small fix of recipe link.
=> Fixed server side rendering recipe link

src/graphql.tsx, test/react-web/client/graphql/queries/errors.test.tsx
- it's really hard to know from which container the error comes from, this should help it a bit.
---
Let me know what you think! Thanks.
=> Added component name in Unhandled error

README.md
since http request is asynchronous.
todos will undefined when render called for the first time.
adding handler for undefined todos
=> fix readme for displaying todos

src/index.js.flow
`TMergedProps` was not used. It seems like a typo to me.
=> Fix Flow type for 'graphql' HOC

Changelog.md, package.json, src/graphql.tsx
This PR updates apollo client to the latest stable for a fix with subscriptions!
=> bump to newer AC version

test/test-utils/test-utils.js
I noticed that there were not tests yet for the MockedProvider so I took the liberty of writing some:) I would love to hear feedback!
There are also no docs available on testing in the [react-apollo-documentation](https://www.apollographql.com/docs/react/). Is there anyone working on this at the moment, if not then I would be up for adding this to the docs:)
=> Added test for the MockedProvider component.

scripts/deploy.sh
#1354 removed all flow-typed so there is no flow-typed directory anymore
=> Remove flow-typed from deploy script

.flowconfig, .travis.yml, Changelog.md, package.json, scripts/deploy.sh, scripts/src/index.js, scripts/webpack.config.js, scripts/webpack.inspect.js, test/flow.js
Get all the the critical safety checks back working!
=> Cleanup master for bundle size and flow

package.json, test/react-web/client/graphql/queries/polling.test.tsx
Was going to change types to `devDependencies` but reverted, leaving the test change.
=> Fix polling.test

package.json
I noticed the tests are running really slowly on CI, so I decided to increase their speed. See [jest docs](http://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server) for more info.
=> Attempt at speeding up the tests

package.json
=> Removed unused dependencies.

Changelog.md, test/client/graphql/mutations/index.test.tsx, test/client/graphql/mutations/lifecycle.test.tsx, test/client/graphql/mutations/queries.test.tsx, test/client/graphql/mutations/recycled-queries.test.tsx, test/test-utils/createClient.ts
First attempt to reduce boilerplate test code.
=> Mutation test cleanup

Changelog.md, package.json, src/index.ts
Also cleaned up the changelog in prep for the release
=> added back in compose

Changelog.md, examples/typescript/src/__generated__/types.ts, examples/typescript/src/queries.ts, package.json, src/Query.tsx, src/graphql.tsx, test/client/Query.test.tsx, test/client/__snapshots__/Query.test.tsx.snap, test/client/graphql/queries/errors.test.tsx
This implements passing `errorPolicy` to the `Query` component and fixes the usage of `all` when using the HOC.
=> Error and data

Changelog.md, src/graphql.tsx, src/query-hoc.tsx, test/client/graphql/queries/errors.test.tsx
=> Silence errors by default

Changelog.md, package.json
=> ready for release

src/Mutation.tsx
=> Updated Types for Mutation Component

examples/base/package.json, examples/base/src/__tests__/App.js, examples/components/package.json, examples/components/src/__tests__/app.js, test-examples.sh
This is a small cleanup of the example code
=> Cleanup of the example code

src/test-links.ts, src/test-utils.tsx, test/__snapshots__/test-utils.test.tsx.snap, test/client/Query.test.tsx
Added a `__typename` for mock links and mocked provider, per discussion with @jbaxleyiii
=> Added typename to mocked provider

test/flow-usage.js
=> Very minor typo 🐝

README.md
Fix link to apollo 2 migration docs
- [x ] docs
=> fix readme concerning apollo migration

.circleci/config.yml
=> Drop Node 9 for CI; Add in Node 10

Changelog.md, package-lock.json, package.json
`rollup-plugin-babel-minify` is no longer needed, so let's get rid of it.
=> Remove `rollup-plugin-babel-minify` as it's no longer being used

README.md
=> docs(readme): Add section for polyfills

src/parser.ts
=> Fixed typo in error message

Changelog.md, package-lock.json, package.json, src/Query.tsx, src/queryRecycler.ts, src/types.ts, test/__snapshots__/test-utils.test.tsx.snap, test/client/Query.test.tsx, test/client/graphql/queries/errors.test.tsx, test/client/graphql/queries/index.test.tsx
This PR will track changes needed to accommodate Apollo Client 2.6.
=> Apollo Client 2.6 integration work

packages/hooks/src/__tests__/useMutation.test.tsx
Adding an additional test to verify https://github.com/apollographql/react-apollo/issues/3128.
=> Additional test to verify `useMutation` can be used in an effect

packages/hooks/src/__tests__/useQuery.test.tsx
Tests to help validate https://github.com/apollographql/react-apollo/issues/3129.
=> Add `useQuery` start/stop polling test

packages/ssr/src/__tests__/useQuery.test.tsx
Test to validate https://github.com/apollographql/react-apollo/issues/3130.
=> Test to verify SSR is skipped when setting `ssr` to `false`

packages/hoc/src/__tests__/queries/observableQuery.test.tsx, packages/hooks/src/data/MutationData.ts, packages/hooks/src/data/OperationData.ts, packages/hooks/src/data/QueryData.ts
Fixes https://github.com/apollographql/react-apollo/issues/3206.
=> Fix missing initial `false` loading status when using `cache-and-network`
